services:
  # MongoDB
  worlde-db:
    container_name: wordle-db
    image: mongo:6.0.3
    env_file:
      - .env
    ports:
      - "5432:5432"

  # Initial Seed - Will exit when default data is imported
  mongo-seed:
    env_file:
      - .env
    build:
      context: ./wordlist-fixtures
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DOCKER_DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

  node-backend:
    build:
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: node-backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: npm run dev
