services:
  # MongoDB
  worlde-db:
    container_name: wordle-db
    image: mongo:6.0.3
    env_file:
      - .env
    ports:
      - "27017:27017"

  # Initial Seed - Will exit when default data is imported
  mongo-seed:
    env_file:
      - .env
    build:
      context: ./wordlist-fixtures
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DOCKER_DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - wordle-db
